# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    working_directory: ~/SeriesGuide

    docker:
      - image: circleci/android:api-28

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assembleDebug

      - run:
          name: Run Tests
          command: ./gradlew :app:test
      - store_test_results:
          path: app/build/test-results

      - run:
          # To speed up lint check only run for release variant and only on app module
          # Note: the app module has lintOptions.checkDependencies true, so submodules will be checked
          # Source: https://groups.google.com/forum/#!topic/lint-dev/RGTvK_uHQGQ
          name: Run Lint
          command: ./gradlew :app:lintPureRelease :app:lintAmazonRelease
      - store_artifacts:
          path: app/build/reports/lint-results-pureRelease.html
          destination: lint-results-goog.html
      - store_artifacts:
          path: app/build/reports/lint-results-amazonRelease.html
          destination: lint-results-amaz.html

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
